// Test-only portfolio payloads with made-up values. Never imported by app code.

const AS_OF = '2026-10-06T15:00:00+00:00';

const position = (over: Record<string, unknown>) => ({
  key: 'manual-1',
  book: 'manual',
  holding_id: 1,
  symbol: 'QQQ',
  label: 'QQQ',
  asset_class: 'etf',
  account: 'Brokerage',
  quantity: 10,
  price: 500,
  price_source: 'Imported end-of-day close, dataset #1',
  price_as_of: '2026-10-05',
  stale: false,
  stale_reason: null,
  value: 5000,
  weight: 0.8333,
  greeks: null,
  notes: [],
  ...over,
});

export const portfolioPayload = {
  as_of: AS_OF,
  source: 'Your holdings (local SQLite), imported prices and quotes, and the Alpaca paper account',
  book: 'manual',
  benchmark: 'SPY',
  window: 252,
  paper: { status: 'not_requested', detail: 'Manual holdings only.' },
  positions: [
    position({}),
    position({
      key: 'manual-2',
      holding_id: 2,
      symbol: 'Cash',
      label: 'Cash',
      asset_class: 'cash',
      account: 'Bank',
      quantity: 1000,
      price: 1,
      price_source: 'Cash at face value',
      price_as_of: '2026-10-06',
      value: 1000,
      weight: 0.1667,
    }),
    position({
      key: 'manual-3',
      holding_id: 3,
      symbol: 'ZZZ',
      label: 'ZZZ',
      asset_class: 'stock',
      price: null,
      price_source: null,
      price_as_of: null,
      value: null,
      weight: null,
      notes: ['No imported bars and no manual price: not valued.'],
    }),
  ],
  total_value: 6000,
  long_value: 6000,
  allocation: [
    { asset_class: 'etf', value: 5000, weight: 0.8333 },
    { asset_class: 'cash', value: 1000, weight: 0.1667 },
  ],
  concentration: { hhi: 1, effective_n: 1, top: [['QQQ', 1]], top5_weight: 1 },
  risk: {
    start: '2025-10-03',
    end: '2026-10-05',
    returns: 252,
    volatility: 0.1834,
    max_drawdown: -0.1212,
    benchmark_volatility: 0.16,
    beta: 0.95,
    correlation: 0.91,
  },
  risk_note: '',
  risk_included: ['QQQ'],
  risk_excluded: [],
  coverage: 1,
  price_basis: 'Adjusted closes (dividends and splits included)',
  greeks_total: null,
  greeks_missing: [],
  tips: [
    {
      id: 'largest_position',
      title: 'Largest position',
      status: 'fired',
      observed: 'QQQ is 100.0% of non-cash long value',
      threshold: 'fires above 20.0%',
      detail: "One position's moves drive much of the result when its weight is high.",
    },
    {
      id: 'unpriced',
      title: 'Unpriced holdings',
      status: 'fired',
      observed: '1 not valued: ZZZ',
      threshold: 'fires on any unpriced holding',
      detail: 'Unpriced holdings are left out of every total; nothing is guessed.',
    },
    {
      id: 'beta',
      title: 'Beta to benchmark',
      status: 'clear',
      observed: 'beta 0.95, correlation 0.91',
      threshold: 'fires above 1.3',
      detail: '',
    },
  ],
  method: "Risk replays today's weights over past daily prices.",
};
